# Generated by Django 2.0.7 on 2018-07-04 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
    ]
